# Generated by Django 3.2.5 on 2021-08-11 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DoiBongApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cauthu',
            name='avatar',
            field=models.CharField(max_length=500, null=True),
        ),
    ]
