# Generated by Django 3.2.5 on 2021-08-11 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DoiBongApp', '0002_alter_cauthu_avatar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cauthu',
            name='height',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='cauthu',
            name='number',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='cauthu',
            name='weight',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
